### PR TITLE
Add --experimental-worker if using Node 10.x

### LINKED ISSUE #39: Fails with "Error: Cannot find module 'worker_threads'"
OS: Debian 10
Node: v10.21.0
Elm: 0.19.1

Trying to run elm-test-rs 0.4.1 for [`malaire/elm-uint64`](https://github.com/malaire/elm-uint64) fails with following error:
```
elm-test-rs 0.4.1
-----------------

Total time spent in the elm compiler: 0.13511102s
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/y/projects/GitHub/elm-uint64/elm-stuff/tests-0.19.1/js/node_supervisor.js:69:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### PR DESCRIPTION
**Pull request by malaire**
Fixes #39

I'm not sure whether this should also check if Node is below 10.5 and then exit with error, as those versions are known not to work.

Tested to work in Debian 10 with Node 10.21.0

### CODE REVIEW

**Comment by mpizenberg** [comment]
> I'm not sure whether this should also check if Node is below 10.5

We can leave it like this.

PS: don't mind the macos tests failure. I'm not sure why when the CI uses the cache, macos fails. I haven't figured this out and fixed it yet.
